---
default_language_version: {python: python3}
minimum_pre_commit_version: "1.15"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: Check for valid YAML syntax in repo
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_yaml.py
      - id: detect-private-key
        name: Check for existence of private key in repo
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/detect_private_key.py
      - id: trailing-whitespace
        name: Remove trailing whitespace in YAML,Bash files
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/trailing_whitespace_fixer.py
        files: \.(sh|yaml|yml)$
      - id: end-of-file-fixer
        name: Ensure EOF is consistently only a newline
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/end_of_file_fixer.py
        files: \.(sh|yaml|yml)$
      - id: mixed-line-ending
        name: Ensure line-ending is consistent
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/mixed_line_ending.py
        files: \.(sh|yaml|yml)$
          #- id: check-executables-have-shebangs
          #  name: Checks that non-binary executables have a proper shebang
          #  description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_executables_have_shebangs.py
          #  files: \.(sh)$
          #- id: check-shebang-scripts-are-executable
          #  name: Checks that scripts with shebangs are executable.
          #  description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_shebang_scripts_are_executable.py
          #  files: \.(sh)$
          #- id: check-json
          #  name: Attempts to load all json files to verify syntax.
          #  description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_json.py
          #  files: \.(json)$
          #- id: check-toml
          #  name: Attempts to load all toml files to verify syntax.
          #  description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_toml.py
          #  files: \.(toml)$
      - id: check-yaml
        name: Attempts to load all yaml files to verify syntax.
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_yaml.py
        files: \.(yaml)$

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
