---
name: CI
'on':
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - init
  schedule:
    - cron: "0 1 * * 1"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      -
        name: Run pre-commit
        run: |
          pip install pre-commit
          make pre-commit-install
          make pre-commit-run

  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: .
            dockerfile: Dockerfile
            tags: |
              toozej/golang-starter:latest
              ghcr.io/toozej/golang-starter:latest
              quay.io/toozej/golang-starter:latest
          - context: .
            dockerfile: Dockerfile.distroless
            tags: |
              toozej/golang-starter:distroless
              ghcr.io/toozej/golang-starter:distroless
              quay.io/toozej/golang-starter:distroless
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        # https://docs.docker.com/docker-hub/access-tokens/
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      -
        name: Login to Quay Container Registry
        uses: docker/login-action@v2
        # https://github.com/marketplace/actions/push-to-registry#examples
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          tags: ${{ matrix.tags }}
          platforms: linux/amd64,linux/arm64
          push: true
