---
name: "grype"

on:
  push:
    branches: ['main', 'init']
  pull_request:

jobs:
  scan-source:
    name: scan-source
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: true

  scan-image:
    name: scan-image
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: anchore/scan-action@v3
        with:
          image: "goreleaser/goreleaser:latest"
          fail-build: true
